import { MigrationInterface, QueryRunner } from "typeorm";

export class DbModelReadjustment1715612633160 implements MigrationInterface {
    name = 'DbModelReadjustment1715612633160'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP CONSTRAINT "FK_78c3812e6b97f6e6b204cbb96f7"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP CONSTRAINT "FK_226b1c91784c64500273634044b"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP CONSTRAINT "FK_2b901dd818a2a6486994d915a68"`);
        await queryRunner.query(`CREATE TABLE "hotel_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hotel_id" uuid NOT NULL, "image_url" character varying NOT NULL, CONSTRAINT "PK_a86256c68fa07ac3301f8113c74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_amenities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "room_id" uuid, "hotel_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3812057aa7d58f8f6dd349c622e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "hotel_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ef520f244ee34141bd897de8009" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "room_id" uuid NOT NULL, "url" text NOT NULL, CONSTRAINT "PK_ac049009c777706919d50237ecf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" text, "hotel_id" uuid NOT NULL, "room_category_id" uuid NOT NULL, "cost_amount" integer NOT NULL, "cost_currency" character varying NOT NULL DEFAULT 'NGN', "status" character varying NOT NULL DEFAULT 'available', "capacity" integer NOT NULL DEFAULT '1', "room_id" character varying NOT NULL, "bed_type" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP CONSTRAINT "REL_78c3812e6b97f6e6b204cbb96f"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP CONSTRAINT "UQ_226b1c91784c64500273634044b"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "should_receive_notifications"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP CONSTRAINT "UQ_2b901dd818a2a6486994d915a68"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "username" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD CONSTRAINT "UQ_333e60f49fb5a92288a8ad9db0a" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD CONSTRAINT "UQ_314b59328cc520a2d0fcc18e080" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "gender" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "date_of_birth" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "phone_number_intl" character varying`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "is_email_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "is_phone_number_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "username" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD CONSTRAINT "UQ_7737150c31836bbed41993344c8" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD CONSTRAINT "UQ_a3c0b808a47f92638a967d770e4" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "gender" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "date_of_birth" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "phone_number_intl" character varying`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "is_email_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "is_phone_number_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "is_waitlist_user" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "username" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admins" ADD CONSTRAINT "UQ_4ba6d0c734d53f8e1b2e24b6c56" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admins" ADD CONSTRAINT "UQ_051db7d37d478a69a7432df1479" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "gender" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "date_of_birth" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "phone_number_intl" character varying`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "is_email_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "is_phone_number_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "is_waitlist_user" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP CONSTRAINT "FK_b5fee77eaa22231307f47bc6954"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ALTER COLUMN "hotel_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD CONSTRAINT "FK_b5fee77eaa22231307f47bc6954" FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_images" ADD CONSTRAINT "FK_65dd867699502f1b83455c128ce" FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "FK_5e0629e1590240525c8248de9e1" FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_amenities" ADD CONSTRAINT "FK_1bbdd33b01f2e52f4dd50743544" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_categories" ADD CONSTRAINT "FK_dcf324bab6c62968c8f9d53b2dd" FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_images" ADD CONSTRAINT "FK_5f4e74488214bfa1d5b6556ddd6" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_7a61484af364d0d804b21b25c7f" FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_bd94a25a58e3979a4b575081431" FOREIGN KEY ("room_category_id") REFERENCES "room_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_bd94a25a58e3979a4b575081431"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_7a61484af364d0d804b21b25c7f"`);
        await queryRunner.query(`ALTER TABLE "room_images" DROP CONSTRAINT "FK_5f4e74488214bfa1d5b6556ddd6"`);
        await queryRunner.query(`ALTER TABLE "room_categories" DROP CONSTRAINT "FK_dcf324bab6c62968c8f9d53b2dd"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "FK_1bbdd33b01f2e52f4dd50743544"`);
        await queryRunner.query(`ALTER TABLE "room_amenities" DROP CONSTRAINT "FK_5e0629e1590240525c8248de9e1"`);
        await queryRunner.query(`ALTER TABLE "hotel_images" DROP CONSTRAINT "FK_65dd867699502f1b83455c128ce"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP CONSTRAINT "FK_b5fee77eaa22231307f47bc6954"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ALTER COLUMN "hotel_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD CONSTRAINT "FK_b5fee77eaa22231307f47bc6954" FOREIGN KEY ("hotel_id") REFERENCES "hotels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "is_waitlist_user"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "is_phone_number_verified"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "is_email_verified"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "phone_number_intl"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP CONSTRAINT "UQ_051db7d37d478a69a7432df1479"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP CONSTRAINT "UQ_4ba6d0c734d53f8e1b2e24b6c56"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "is_waitlist_user"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "is_phone_number_verified"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "is_email_verified"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "phone_number_intl"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP CONSTRAINT "UQ_a3c0b808a47f92638a967d770e4"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP CONSTRAINT "UQ_7737150c31836bbed41993344c8"`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "is_phone_number_verified"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "is_email_verified"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "phone_number_intl"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP CONSTRAINT "UQ_314b59328cc520a2d0fcc18e080"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP CONSTRAINT "UQ_333e60f49fb5a92288a8ad9db0a"`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "admins" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admins" ADD CONSTRAINT "UQ_2b901dd818a2a6486994d915a68" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "should_receive_notifications" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD CONSTRAINT "UQ_226b1c91784c64500273634044b" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD CONSTRAINT "REL_78c3812e6b97f6e6b204cbb96f" UNIQUE ("user_id")`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TABLE "room_images"`);
        await queryRunner.query(`DROP TABLE "room_categories"`);
        await queryRunner.query(`DROP TABLE "room_amenities"`);
        await queryRunner.query(`DROP TABLE "hotel_images"`);
        await queryRunner.query(`ALTER TABLE "admins" ADD CONSTRAINT "FK_2b901dd818a2a6486994d915a68" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hotel_staffs" ADD CONSTRAINT "FK_226b1c91784c64500273634044b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "marketing_agents" ADD CONSTRAINT "FK_78c3812e6b97f6e6b204cbb96f7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
